sudo: required
services:
  - docker

before_install:
  - docker build -t hamzabutt1401/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hamzabutt1401/react-test npm run test -- --coverage

after_success:
  - docker build hamzabutt1401/react-client ./client
  - docker build hamzabutt1401/react-nginx ./nginx
  - docker build hamzabutt1401/react-server ./server
  - docker build hamzabutt1401/react-worker ./worker

  #login in to docker

  - echo "$Docker_password" | docker login -u "$Docker_id" --password-stdin

  #push image into docker

  - docker push hamzabutt1401/react-client
  - docker push hamzabutt1401/react-nginx
  - docker push hamzabutt1401/react-server
  - docker push hamzabutt1401/react-worker