sudo: required
services:
  - docker

before_install:
  - docker build -t hamzabutt1401/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hamzabutt1401/react-test npm run test -- --coverage

after_sucess:
  - docker run hamzabutt1401/multi-client ./client
  - docker run hamzabutt1401/multi-nginx ./nginx
  - docker run hamzabutt1401/multi-server ./server
  - docker run hamzabutt1401/multi-worker ./worker

  #login in to docker

  - echo "$Docker_password" | docker login -u "$Docker_id" --password-stdin

  #push image into docker

  - docker push hamzabutt1401/multi-client
  - docker push hamzabutt1401/multi-nginx
  - docker push hamzabutt1401/multi-server
  - docker push hamzabutt1401/multi-worker